// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNP1nTLveaU0pbk562wVJp_QOWh_ReDrM',
    appId: '1:751880563319:web:111dc6b3d054636459b472',
    messagingSenderId: '751880563319',
    projectId: 'shuttlelounge-f40fc',
    authDomain: 'shuttlelounge-f40fc.firebaseapp.com',
    storageBucket: 'shuttlelounge-f40fc.firebasestorage.app',
    measurementId: 'G-V11KELWZXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3PLuj1zyhLeZATk9ST8-hup79lWw3Qzw',
    appId: '1:751880563319:android:a0b5bb09b67cbbba59b472',
    messagingSenderId: '751880563319',
    projectId: 'shuttlelounge-f40fc',
    storageBucket: 'shuttlelounge-f40fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWF4u3fZhqddqTvgmlIqROw73Mi4_ssc',
    appId: '1:751880563319:ios:bdbdca7c7d38288b59b472',
    messagingSenderId: '751880563319',
    projectId: 'shuttlelounge-f40fc',
    storageBucket: 'shuttlelounge-f40fc.firebasestorage.app',
    iosBundleId: 'com.example.shuttleloungenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWF4u3fZhqddqTvgmlIqROw73Mi4_ssc',
    appId: '1:751880563319:ios:bdbdca7c7d38288b59b472',
    messagingSenderId: '751880563319',
    projectId: 'shuttlelounge-f40fc',
    storageBucket: 'shuttlelounge-f40fc.firebasestorage.app',
    iosBundleId: 'com.example.shuttleloungenew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNP1nTLveaU0pbk562wVJp_QOWh_ReDrM',
    appId: '1:751880563319:web:df0361c88ca6a4ce59b472',
    messagingSenderId: '751880563319',
    projectId: 'shuttlelounge-f40fc',
    authDomain: 'shuttlelounge-f40fc.firebaseapp.com',
    storageBucket: 'shuttlelounge-f40fc.firebasestorage.app',
    measurementId: 'G-EZSYL96Q7R',
  );
}
